### ISSUE TITLE
UNC path is missing sharename: //somefile.js

### ISSUE THREAD

**Issue by TonyRice** [Automately/automately-core#33]
This error should not exist. It exposes error messages that should not reach the user.

**Comment by TonyRice** [comment]
java.nio.file.InvalidPathException: UNC path is missing sharename: //dada-agent.js
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:118)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at automately.core.file.VirtualFileSystem.getFileName(VirtualFileSystem.java:275)
	at automately.core.services.job.script.ScriptContext.require(ScriptContext.java:770)
	at automately.core.services.job.script.ScriptContext$12.call(ScriptContext.java:1507)
	at jdk.nashorn.internal.scripts.Script$Recompilation$5$\^eval\_.:program(<eval>:2)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:623)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at automately.core.services.job.script.ScriptContext.executeScript(ScriptContext.java:1912)
	at automately.core.services.job.script.ScriptContext.execute(ScriptContext.java:1931)
	at automately.core.services.job.JobServer$1.lambda$run$2(JobServer.java:217)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
