### ISSUE TITLE
NullPointerException happens when a job started from startJob() gets stopped after the parent job is stopped.

### ISSUE THREAD

**Issue by TonyRice** [Automately/automately-core#35]
[async-eventloop-thread-6] 22:30:04,451 SEVERE [io.jsync.impl.DefaultContext]  Unhandled exception
java.lang.NullPointerException
        at automately.core.services.job.script.ScriptContext.evaluateAsync(ScriptContext.java:1271)
        at automately.core.services.job.script.objects.core.AutomatelyObject.lambda$startJob$1(AutomatelyObject.java:312)
        at io.jsync.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:962)
        at io.jsync.impl.DefaultContext$3.run(DefaultContext.java:175)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)

**Comment by TonyRice** [comment]
This was being caused by the parent job not unregistering the event handlers on the eventbus
